### Testar a raiz do projeto
GET http://localhost:5078


### Listar todas as tarefas
GET http://localhost:5078/api/tarefas/listar


### Buscar uma tarefa pelo id
GET http://localhost:5078/api/tarefas/buscar/2

### Cadastrar tarefa
POST  http://localhost:5078/api/tarefas/cadastrar
Content-Type: application/json

{
  "nome": "Tarefa 1 "
}
